name: mappka
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # 1. Local storage and files (offline mod)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # 2. Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.6.12

  # 3. Work with device
  geolocator: ^13.0.1      
  camera: ^0.10.6          
  sensors_plus: ^6.1.1    
  battery_plus: ^6.1.1    

  # 4. Work with map
  flutter_map: ^6.1.0      
  latlong2: ^0.9.1         

  # 5. Architecture
  flutter_bloc: ^8.1.6
  equatable: ^2.0.8
  go_router: ^17.2.3
  sqflite: ^2.4.2+1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 6. Code generators
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/map/lviv_test.geojson