// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARki3H7G5-GOS9adiNnGRYWlYzys2Cuqc',
    appId: '1:994585830613:web:45815d0b583b9fbdb5ee5c',
    messagingSenderId: '994585830613',
    projectId: 'mappka-208e9',
    authDomain: 'mappka-208e9.firebaseapp.com',
    storageBucket: 'mappka-208e9.firebasestorage.app',
    measurementId: 'G-C53N9ZDQCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvp-_RWEUyk73HPML-tTweCcZ4RRy0j0I',
    appId: '1:994585830613:android:6b8890f49fddf4b2b5ee5c',
    messagingSenderId: '994585830613',
    projectId: 'mappka-208e9',
    storageBucket: 'mappka-208e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtM27NxASRc-eEhAomUnh6nLLL1CR33bg',
    appId: '1:994585830613:ios:93493762c0540a49b5ee5c',
    messagingSenderId: '994585830613',
    projectId: 'mappka-208e9',
    storageBucket: 'mappka-208e9.firebasestorage.app',
    iosBundleId: 'com.example.mappka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtM27NxASRc-eEhAomUnh6nLLL1CR33bg',
    appId: '1:994585830613:ios:93493762c0540a49b5ee5c',
    messagingSenderId: '994585830613',
    projectId: 'mappka-208e9',
    storageBucket: 'mappka-208e9.firebasestorage.app',
    iosBundleId: 'com.example.mappka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARki3H7G5-GOS9adiNnGRYWlYzys2Cuqc',
    appId: '1:994585830613:web:340e79e937e0d322b5ee5c',
    messagingSenderId: '994585830613',
    projectId: 'mappka-208e9',
    authDomain: 'mappka-208e9.firebaseapp.com',
    storageBucket: 'mappka-208e9.firebasestorage.app',
    measurementId: 'G-ZSKR49K9WQ',
  );
}
